sonar.projectKey=liatoshynsky-foundation

sonar.sources=.

sonar.tests=.

sonar.test.inclusions=\
**/test/**,\
**/tests/**,\
**/spec/**,\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/*.mock.ts,\
**/test-*.ts

sonar.coverage.exclusions=\
**/test/**,\
**/tests/**,\
**/spec/**,\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/*.mock.ts

sonar.cpd.exclusions=\
**/test/**,\
**/tests/**,\
**/spec/**,\
**/*.spec.ts,\
**/*.test.ts,\
**/__tests__/**,\
**/*.mock.ts
