import { render, screen } from '@testing-library/react';
import React from 'react';

import ImageWithCaption, { BorderProps } from './ImageWithCaption';
import { TipTapNodeTypes } from '~/types/enums/common.enums';
import { ElementSizes } from '~/types/types/common.types';
import { TipTapDoc } from '~/types/types/tiptap.types';

type MockTipTapContentProps = {
  data?: TipTapDoc;
  nodeRenderers?: Record<string, (children: React.ReactNode) => React.ReactNode>;
};

jest.mock('next-intl', () => ({
  useLocale: () => 'en'
}));

jest.mock('next/image', () => ({
  __esModule: true,
  default: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <img {...props} data-testid="next-image" />
}));

jest.mock('~/lib/utils/generateSizesAttribute', () => ({
  generateSizesAttribute: jest.fn(() => '(max-width: 600px) 300px')
}));

jest.mock('~/lib/utils/tiptapHelpers', () => ({
  isTipTapDoc: jest.fn((val) => val && val.type === 'doc'),
  getPlainString: jest.fn((val) => (typeof val === 'string' ? val : val?.en || 'localized-string')),
  extractTextFromTipTap: jest.fn(() => 'extracted-tiptap-alt-text')
}));

jest.mock('~/components/tip-tap-content/TipTapContent', () => ({
  __esModule: true,
  default: ({ nodeRenderers }: MockTipTapContentProps) => {
    const ParagraphRenderer = nodeRenderers?.[TipTapNodeTypes.paragraph] || nodeRenderers?.['paragraph'];
    return (
      <div data-testid="mock-tiptap-caption">
        {ParagraphRenderer ? ParagraphRenderer('Mocked TipTap Caption') : 'Fallback'}
      </div>
    );
  }
}));

const defaultSizes: ElementSizes = {
  width: { xs: 300, sm: 600, md: 900 },
  height: { xs: 200, sm: 400, md: 600 }
};

const mockTipTapData = { type: 'doc', content: [] } as unknown as TipTapDoc;

describe('ImageWithCaption', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Basic Rendering & Attributes', () => {
    it('should render the image with the correct basic attributes', () => {
      render(
        <ImageWithCaption
          src="/test.jpg"
          alt="Test image"
          sizes={defaultSizes}
          caption="Test Caption"
          dataTestId="image-wrapper"
        />
      );

      const wrapper = screen.getByTestId('image-wrapper');
      const img = screen.getByTestId('next-image');

      expect(wrapper).toBeInTheDocument();
      expect(img).toBeInTheDocument();
      expect(img).toHaveAttribute('src', '/test.jpg');
    });

    it('should apply the sizes attribute generated by the utility function', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} />);

      const img = screen.getByTestId('next-image');
      expect(img).toHaveAttribute('sizes', '(max-width: 600px) 300px');
    });

    it('should render the border box when border props are provided', () => {
      const borderProps: BorderProps = {
        sizes: defaultSizes,
        top: { xs: 20 },
        left: { xs: 30 }
      };

      render(
        <ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} border={borderProps} />
      );

      expect(screen.getByTestId('img-border')).toBeInTheDocument();
    });
  });

  describe('Alt Text Resolution', () => {
    it('should resolve standard string or localized alt text using getPlainString', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Standard Alt" sizes={defaultSizes} caption={null} />);

      const img = screen.getByTestId('next-image');
      expect(img).toHaveAttribute('alt', 'Standard Alt');
    });

    it('should resolve TipTap alt text using extractTextFromTipTap', () => {
      render(<ImageWithCaption src="/test.jpg" alt={mockTipTapData as any} sizes={defaultSizes} caption={null} />);

      const img = screen.getByTestId('next-image');
      expect(img).toHaveAttribute('alt', 'extracted-tiptap-alt-text');
    });
  });

  describe('Caption Rendering', () => {
    it('should render a standard string caption using Typography', () => {
      render(
        <ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption="Standard String Caption" />
      );

      expect(screen.getByText('Standard String Caption')).toBeInTheDocument();
      expect(screen.queryByTestId('mock-tiptap-caption')).not.toBeInTheDocument();
    });

    it('should render a TipTap caption using the TipTapContent component', () => {
      render(
        <ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={mockTipTapData as any} />
      );

      const tiptapContainer = screen.getByTestId('mock-tiptap-caption');
      expect(tiptapContainer).toBeInTheDocument();

      expect(tiptapContainer).toHaveTextContent('Mocked TipTap Caption');
    });

    it('should safely render without a caption if null is provided', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} />);
      expect(screen.getByTestId('next-image')).toBeInTheDocument();
      expect(screen.queryByTestId('mock-tiptap-caption')).not.toBeInTheDocument();
    });
  });
});
