import { render, screen } from '@testing-library/react';
import { JSONContent } from '@tiptap/react';
import React from 'react';

import ImageWithCaption, { BorderProps } from './ImageWithCaption';
import { TipTapNodeTypes } from '~/types/enums/common.enums';
import { ElementSizes } from '~/types/types/common.types';
import { TipTapDoc } from '~/types/types/tiptap.types';

type MockTipTapContentProps = {
  data?: TipTapDoc;
  nodeRenderers?: Record<string, (children: React.ReactNode) => React.ReactNode>;
};

jest.mock('next-intl', () => ({
  useLocale: () => 'en'
}));

jest.mock('next/image', () => ({
  __esModule: true,
  default: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <img {...props} alt="" data-testid="next-image" />
}));

jest.mock('~/lib/utils/generateSizesAttribute', () => ({
  generateSizesAttribute: jest.fn(() => '(max-width: 600px) 300px')
}));

jest.mock('~/lib/utils/tiptapHelpers', () => ({
  isTipTapDoc: jest.fn((val) => val?.type === 'doc'),
  getPlainString: jest.fn((val) => (typeof val === 'string' ? val : val?.en || 'localized-string')),
  extractTextFromTipTap: jest.fn(() => 'extracted-tiptap-alt-text')
}));

jest.mock('~/components/tip-tap-content/TipTapContent', () => ({
  __esModule: true,
  default: ({ nodeRenderers }: MockTipTapContentProps) => {
    const ParagraphRenderer = nodeRenderers?.[TipTapNodeTypes.paragraph] || nodeRenderers?.['paragraph'];
    return (
      <div data-testid="mock-tiptap-caption">
        {ParagraphRenderer ? ParagraphRenderer('Mocked TipTap Caption') : 'Fallback'}
      </div>
    );
  }
}));

const defaultSizes: ElementSizes = {
  width: { xs: 300, sm: 600, md: 900 },
  height: { xs: 200, sm: 400, md: 600 }
};

const mockTipTapData = {
  type: 'doc',
  content: [
    {
      type: 'paragraph',
      content: [
        {
          type: 'text',
          text: 'extracted-tiptap-alt-text'
        }
      ]
    }
  ]
} as unknown as JSONContent;

describe('ImageWithCaption', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Basic Rendering & Attributes', () => {
    it('should render the image with the correct basic attributes', () => {
      render(
        <ImageWithCaption
          src="/test.jpg"
          alt="Test image"
          sizes={defaultSizes}
          caption="Test Caption"
          dataTestId="image-wrapper"
        />
      );

      expect(screen.getByTestId('image-wrapper')).toBeInTheDocument();

      const img = screen.getByTestId('next-image');
      expect(img).toBeInTheDocument();
      expect(img).toHaveAttribute('src', '/test.jpg');
    });

    it('should apply the sizes attribute generated by the utility function', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} />);

      expect(screen.getByTestId('next-image')).toHaveAttribute('sizes', '(max-width: 600px) 300px');
    });

    it('should render the border box when border props are provided', () => {
      const borderProps: BorderProps = {
        sizes: defaultSizes,
        top: { xs: 20 },
        left: { xs: 30 }
      };

      render(
        <ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} border={borderProps} />
      );

      expect(screen.getByTestId('img-border')).toBeInTheDocument();
    });
  });

  describe('Alt Text Resolution Matrix', () => {
    const altResolutionCases = [
      {
        label: 'standard string or localized variant inputs',
        altInput: 'Standard Alt',
        expectedAttribute: 'Standard Alt'
      },
      {
        label: 'structured TipTap content payloads',
        altInput: mockTipTapData,
        expectedAttribute: 'extracted-tiptap-alt-text'
      }
    ];

    it.each(altResolutionCases)(
      'should resolve alt properties accurately for $label',
      ({ altInput, expectedAttribute }) => {
        render(<ImageWithCaption src="/test.jpg" alt={altInput} sizes={defaultSizes} caption={null} />);

        expect(screen.getByTestId('next-image')).toHaveAttribute('alt', expectedAttribute);
      }
    );
  });

  describe('Caption Conditional Pipelines', () => {
    it('should render a standard primitive string caption block using Typography', () => {
      render(
        <ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption="Standard String Caption" />
      );

      expect(screen.getByText('Standard String Caption')).toBeInTheDocument();
      expect(screen.queryByTestId('mock-tiptap-caption')).not.toBeInTheDocument();
    });

    it('should map layout node factory renderers and mount TipTapContent when fed a document data profile', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={mockTipTapData} />);

      const tiptapContainer = screen.getByTestId('mock-tiptap-caption');
      expect(tiptapContainer).toBeInTheDocument();
      expect(tiptapContainer).toHaveTextContent('Mocked TipTap Caption');
    });

    it('should completely ignore and clean layout structures if an explicit null value is set', () => {
      render(<ImageWithCaption src="/test.jpg" alt="Test image" sizes={defaultSizes} caption={null} />);

      expect(screen.getByTestId('next-image')).toBeInTheDocument();
      expect(screen.queryByTestId('mock-tiptap-caption')).not.toBeInTheDocument();
    });
  });
});
