export const styles = {
  container: {
    width: '100%',
    maxWidth: '328px',
    fontFamily: 'var(--font-mulish)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '24px',
    pl: '12px',
    pt: '12px',
    pb: '24px',
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    width: '100%',
    maxWidth: { xs: '258px', md: '296px' },
  },
  photoWrapper: {
    position: 'relative',
    width: '207px',
    height: '173px',
    overflow: 'hidden',
    transform: 'rotate(-25deg)',
    borderRadius: '50%',
    backgroundColor: '#B8AEA2',
  },
  textWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    color: '#190D03',
  },
  name: {
    fontSize: { xs: '20px', md: '24px' },
    fontWeight: 700,
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  description: {
    fontSize: { xs: '16px', md: '20px' },
    fontWeight: 400,
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  logoWrapper: {
    display: 'flex',
    alignItems: { xs: 'center', md: 'end' },
    justifyContent: { xs: 'center', md: 'left' },
    width: { xs: '258px', md: '296px' },
    height: { xs: '180px', md: '132px' },
  },
  logo: {
    width: { xs: '210px', md: '236px' },
    height: { xs: '78px', md: '88px' },
  },
};
