import '../globals.css';
import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mulish, Oswald } from 'next/font/google';
import { cookies } from 'next/headers';
import { notFound } from 'next/navigation';
import { hasLocale, Locale, NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';

import Footer from '~/components/Footer/Footer';
import ThemeProvider from '~/ds-components/theme/ThemeProvider';

import { styles } from './layout.styles';

import { routing } from '~/i18n/routing';
import CookieModalWrapper from '~/shared/components/cookie-modal/CookieModalWrapper';
import EmotionProvider from '~/shared/components/emotion-provider/EmotionProvider';
import ConsentScript from '~/shared/components/google-tracking/ConsentScript';
import Header from '~/shared/components/Header/Header.server';
import { AudioPlayerProvider } from '~/shared/context/AudioPlayerContext';
import QueryProvider from '~/shared/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-mulish'
});

const oswald = Oswald({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600', '700'],
  variable: '--font-oswald'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutParams {
  readonly children: ReactNode;
  readonly params: Promise<{ readonly lang: Locale }>;
}

export default async function RootLayout({ children, params }: RootLayoutParams) {
  const { lang } = await params;
  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }

  const cookieList = await cookies();
  const cookieConsent = cookieList.get('cookie_consent')?.value || '';

  return (
    <html lang={lang}>
      <head>
        <meta name="emotion-insertion-point" content="" />
        <ConsentScript
          trackingId={process.env.TRACKING_ID || ''}
          gtmId={process.env.GTM_ID || ''}
          consent_cookie={cookieConsent}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} ${oswald.variable}`}>
        <EmotionProvider>
          <NextIntlClientProvider>
            <ThemeProvider>
              <QueryProvider>
                <AudioPlayerProvider>
                  <Box sx={styles.container}>
                    <Header />
                    <Box sx={styles.childrenBox}>{children}</Box>
                    <Footer />
                  </Box>
                  <CookieModalWrapper cookie_consent={cookieConsent} />
                </AudioPlayerProvider>
              </QueryProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
