import '../globals.css';
import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mulish, Oswald } from 'next/font/google';
import { cookies } from 'next/headers';
import { notFound } from 'next/navigation';
import { hasLocale, Locale, NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';

import Footer from '~/components/Footer/Footer';
import Header from '~/components/Header/Header';
import { theme } from '~/ds-components/theme/Theme';
import ThemeProvider from '~/ds-components/theme/ThemeProvider';

import { routing } from '~/i18n/routing';
import { ColumnGuides } from '~/shared/components/column-guides/ColumnGuides';
import CookieModalWrapper from '~/shared/components/cookie-modal/CookieModalWrapper';
import EmotionProvider from '~/shared/components/emotion-provider/EmotionProvider';
import QueryProvider from '~/shared/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-mulish'
});

const oswald = Oswald({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600', '700'],
  variable: '--font-oswald'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutParams {
  readonly children: ReactNode;
  readonly params: Promise<{ readonly lang: Locale }>;
}

export default async function RootLayout({ children, params }: RootLayoutParams) {
  const { lang } = await params;
  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }

  const cookieList = await cookies();
  const cookieConsent = cookieList.get('cookie_consent')?.value || '';

  return (
    <html lang={lang}>
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} ${oswald.variable}`}>
        <EmotionProvider>
          <NextIntlClientProvider>
            <ThemeProvider>
              <QueryProvider>
                <Box sx={{ display: 'flex', flexDirection: 'column', position: 'relative', width: '100vw' }}>
                  <ColumnGuides />
                  <Box
                    sx={{
                      padding: '20px 72px',
                      height: '100vh',
                      display: 'grid',
                      gridTemplateColumns: 'repeat(12, 1fr)',
                      columnGap: '40px',
                      maxWidth: '1920px ',
                      marginLeft: 'auto',
                      marginRight: 'auto',
                      width: '100%',
                      flex: '1',
                      [theme.breakpoints.down('md')]: {
                        gridTemplateColumns: 'repeat(8, 1fr)',
                        paddingLeft: '56px',
                        paddingRight: '56px',
                        columnGap: '20px'
                      },
                      [theme.breakpoints.down('sm')]: {
                        gridTemplateColumns: 'repeat(4, 1fr)',
                        paddingLeft: '24px',
                        paddingRight: '24px',
                        columnGap: '16px'
                      }
                    }}
                  >
                    <Box sx={{ gridColumn: '1 / -1' }}>
                      <Header />
                    </Box>
                    <Box sx={{ display: 'grid', gridTemplateColumns: 'subgrid', gridColumn: '1 / -1' }}>{children}</Box>
                    <Box sx={{ gridColumn: '1 / -1' }}>
                      <Footer />
                    </Box>
                  </Box>
                </Box>
                <CookieModalWrapper cookie_consent={cookieConsent} tracking_id={process.env.TRACKING_ID || ''} />
              </QueryProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
