name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - "release/*"

jobs:
  deploy:
    uses: Liatoshynsky-Foundation/lf-devops/.github/workflows/reusable-cd.yml@feat/0/rework-ci-cd
    with:
      project-name: lf-client
      azure-registry: https://lfacrstage-bkg7bmd7gacxh9e5.azurecr.io/
      azure-username-secret: AzureAppService_ContainerUsername_b9f545afba4f47a2a25a9fb5462ebe38
      azure-password-secret: AzureAppService_ContainerPassword_f3693858f44448dcae56c7ae9296ed93
      azure-image-name: lf-stage-client
      deploy-azure: ${{ github.ref == 'refs/heads/develop' }}
      azure-app-name: lf-client-stage
      azure-publish-profile-secret: AzureAppService_PublishProfile_33658204638a4070adadb0337bf888b8
      azure-slot-name: production
