name: PR (develop)

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  run-lint:
    name: Run ESLint
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        shell: bash
        run: |
          set +e
          npm run lint > full-lint.log 2>&1
          exit_code="${PIPESTATUS[0]}"
          set -e

          SUMMARY_FILE="summary-lint-errors.log"
          grep -B 1 -E '\[warn\]|Error:|Warning:' full-lint.log > "$SUMMARY_FILE" || true

          if [ ! -s "$SUMMARY_FILE" ]; then
            echo "✅ No lint errors found." > "$SUMMARY_FILE"
          fi

          if [ "$exit_code" -ne 0 ]; then
            echo "❌ ESLint errors found."
          else
            echo "✅ No lint errors."
          fi

          exit "$exit_code"

      - name: Upload lint logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: |
            full-lint.log
            summary-lint-errors.log

  run-tests:
    name: Run Tests
    runs-on: 'ubuntu-latest'
    needs: [ 'run-lint' ]

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests and generate logs
        run: |
          echo "🚀 Run Tests..."
          
          npm run test -- --ci 2>&1 | tee "full-tests-results-${{ matrix.node-version }}.log"
          
          exit_code="${PIPESTATUS[0]}"
          SUMMARY_ERRORS_FILE="summary-tests-errors-${{ matrix.node-version }}.log"

          grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-results-${{ matrix.node-version }}.log" > \
            summary-tests-results-${{ matrix.node-version }}.log || \
            echo "❌ Test summary not found." > summary-tests-results-${{ matrix.node-version }}.log

          > "$SUMMARY_ERRORS_FILE"
          if [ "$exit_code" -ne 0 ]; then
            grep -iE "(fail|error|unhandled|exception)" "full-tests-results-${{ matrix.node-version }}.log" >> "$SUMMARY_ERRORS_FILE" || true

            if [ ! -s "$SUMMARY_ERRORS_FILE" ]; then
              echo "Tests failed but no detailed error messages found in logs." >> "$SUMMARY_ERRORS_FILE"
            fi
          
            echo ""
            echo "❌ Tests are failed. Please check $SUMMARY_ERRORS_FILE."
            echo ""
          else
            echo "✅ All tests passed successfully." > "$SUMMARY_ERRORS_FILE"
            echo ""
            echo "✅ All tests are passed successfully."
            echo ""
          fi
          
          exit "$exit_code"

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-results-${{ matrix.node-version }}
          path: |
            full-tests-results-${{ matrix.node-version }}.log
            summary-tests-results-${{ matrix.node-version }}.log
            summary-tests-errors-${{ matrix.node-version }}.log



  docker-build:
    name: Build Docker Container
    runs-on: 'ubuntu-latest'
    needs: [ 'run-lint', 'run-tests' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          LOG_FILE=docker-build-${{ github.sha }}.log
          
          {
          docker build -t my-app-image:${{ github.sha }} . 
          docker image inspect my-app-image:${{ github.sha }} > /dev/null
          echo "✅ Docker image built successfully."
          } >"$LOG_FILE" 2>&1 || {
            echo "❌ Docker build failed. See log." >> "$LOG_FILE"
            exit 1
          }

      - name: Upload Docker Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-results
          path: docker-build-${{ github.sha }}.log


  generate-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [ 'run-lint', 'run-tests', 'docker-build' ]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine overall status
        id: overall_status
        env:
          LINT_JOB_RESULT_ENV: ${{ needs.run-lint.result }}
          TEST_JOB_RESULT_ENV: ${{ needs.run-tests.result }}
          DOCKER_BUILD_JOB_RESULT_ENV: ${{ needs.docker-build.result }}
        run: |
          OVERALL_ICON_VAR="✅"

          if [[ "$LINT_JOB_RESULT_ENV" != "success" || \
                "$TEST_JOB_RESULT_ENV" != "success" || \
                "$DOCKER_BUILD_JOB_RESULT_ENV" != "success" ]]; then
            OVERALL_ICON_VAR="❌"
          fi

          echo "OVERALL_ICON=$OVERALL_ICON_VAR" >> $GITHUB_OUTPUT

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Generate Test Report
        run: |
          CI_MARKER_BASE=" CI Report"
          OVERALL_ICON_FROM_STEP="${{ steps.overall_status.outputs.OVERALL_ICON }}"
          CI_MARKER="# $OVERALL_ICON_FROM_STEP $CI_MARKER_BASE - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"

          {
            echo "$CI_MARKER"
            echo ""
          } > report.txt

          function print_section() {
            local title=$1
            local fallback_msg=$2
            local file_path=$3

            echo "## $title"
            echo ""
            if [[ -f "$file_path" ]]; then
              echo '```'
              cat "$file_path"
              echo '```'
            else
              echo "$fallback_msg"
            fi
            printf "\n"
          }

          LINT_SUMMARY_PATH="${{ github.workspace }}/all-artifacts/lint-results/summary-lint-errors.log"
          print_section "📝 Lint Report" "⚠️ Lint report not found." "$LINT_SUMMARY_PATH" >> report.txt

          echo "## 🧪 Test Results" >> report.txt
          echo "" >> report.txt

          TEST_REPORTS_FOUND=false
          for folder in $(find all-artifacts -maxdepth 1 -type d -name "tests-results-*"); do
            TEST_REPORTS_FOUND=true
            NODE_VERSION_FROM_FOLDER_NAME=$(basename "$folder" | sed 's/tests-results-//')

            SUMMARY_RESULTS_FILE_PATH="$folder/summary-tests-results-${NODE_VERSION_FROM_FOLDER_NAME}.log"
            ERRORS_FILE_PATH="$folder/summary-tests-errors-${NODE_VERSION_FROM_FOLDER_NAME}.log" 

            echo "**🔹 Node.js Version:** $NODE_VERSION_FROM_FOLDER_NAME" >> report.txt
            echo "" >> report.txt

            print_section "**Test Summary:**" "⚠️ No test summary for Node $NODE_VERSION_FROM_FOLDER_NAME." "$SUMMARY_RESULTS_FILE_PATH" >> report.txt
            TESTS_SUCCESSFUL="✅ All tests passed successfully."

            if [[ -f "$ERRORS_FILE_PATH" ]]; then
              if [[ -s "$ERRORS_FILE_PATH" ]] && ! grep -q "$TESTS_SUCCESSFUL" "$ERRORS_FILE_PATH"; then
                print_section "**❌ Test Errors:**" "" "$ERRORS_FILE_PATH" >> report.txt
              elif grep -q "$TESTS_SUCCESSFUL" "$ERRORS_FILE_PATH"; then
                echo '```' >> report.txt
                echo "$TESTS_SUCCESSFUL for Node $NODE_VERSION_FROM_FOLDER_NAME." >> report.txt
                echo '```' >> report.txt
              elif [ ! -s "$ERRORS_FILE_PATH" ]; then
                echo "⚠️ Empty test error log for Node $NODE_VERSION_FROM_FOLDER_NAME." >> report.txt
              fi
            else 
              echo "⚠️ No error log for Node $NODE_VERSION_FROM_FOLDER_NAME." >> report.txt
            fi
            printf "\n" >> report.txt
          done

          if [[ "$TEST_REPORTS_FOUND" == false ]]; then
            echo "⚠️ No test results available." >> report.txt
          fi

          DOCKER_LOG="all-artifacts/docker-results/docker-build-${{ github.sha }}.log"
          {
            echo "## 🐳 Docker Health Check"
            echo ""

            DOCKER_LOG="all-artifacts/docker-results/docker-build-${{ github.sha }}.log"
            DOCKER_SUCCESSFUL="✅ Docker image built successfully"
            DOCKER_FAILED="❌ Docker Build Failed"
            if [[ -f "$DOCKER_LOG" ]]; then
              if grep -q "$DOCKER_FAILED" "$DOCKER_LOG"; then
                echo "**$DOCKER_FAILED:**"
                echo '```log'
                cat "$DOCKER_LOG"
                echo '```'
              else
                echo "$DOCKER_SUCCESSFUL"
              fi
            else
              echo "⚠️ No Docker check log found."
            fi
            printf "\n"
          } >> report.txt

      - name: Publish Report in GitHub Actions Summary
        run: cat report.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Update CI Report in PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR associated, skipping update."
            exit 0
          fi
          
          TARGET_COMMENT_AUTHOR="github-actions[bot]" 
          TARGET_COMMENT_MARKER=" CI Report"
          
          JQ_QUERY_STRING=".[] | select(.user.login==\"$TARGET_COMMENT_AUTHOR\" and (.body | contains(\"$TARGET_COMMENT_MARKER\"))) | .id"
          
          COMMENT_ID=$(gh api "repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
            --jq "$JQ_QUERY_STRING" | head -n 1)
          
          REPORT_CONTENT_FILE="report.txt" 
          
          if [[ -n "$COMMENT_ID" ]]; then
            gh api "repos/${{ github.repository }}/issues/comments/$COMMENT_ID" \
              -X PATCH \
              --field body="$(cat $REPORT_CONTENT_FILE)" 
          else
            gh pr comment "$PR_NUMBER" --body-file "$REPORT_CONTENT_FILE"
          fi